### ISSUE TITLE
[copytool] limit number of requests in work-queue

### ISSUE THREAD

**Issue by ironMann** [tstibor/ltsm#11]
Lustre MDT has the `max_requests` hsm [parameter](http://doc.lustre.org/lustre_manual.pdf#page=202), but it only applies to the appropriate MDT HSM coordinator. This makes it tricky to configure properly, because it's not connected to number of registered copytools. Ideally, it should be set to some value above total number of threads in all of the registered copytools.

Since there's a good chance for miss-configuration, I propose we limit number of request we take for hsm.  How about setting the limit to `2 x thread_count`?

**Comment by tstibor** [comment]
Thanks for the patch.

I just found an issue from commit https://github.com/tstibor/ltsm/commit/d1853aabf16b5bff9219d5d7a000693828800a78
to https://github.com/tstibor/ltsm/commit/175aca88ce628d75dbdfd32c01eedf27fb5e189d

When on TSM server option is set: `Maximum Mount Points Allowed: 8` 
and number of threads is 10. Then the archiving process hangs:

```
root@lxdv81:/lustre/tmp/tmp.u2dDJJSDRU# lfs hsm_state *
3EPZ: (0x00000009) exists archived, archive_id:1
7gjU: (0x00000009) exists archived, archive_id:1
91X4: (0x00000009) exists archived, archive_id:1
cqte: (0x00000009) exists archived, archive_id:1
dTCH: (0x00000009) exists archived, archive_id:1
gfw1: (0x00000001) exists, archive_id:1
GxOo: (0x00000009) exists archived, archive_id:1
JkO5: (0x00000009) exists archived, archive_id:1
K3iV: (0x00000009) exists archived, archive_id:1
kBp5: (0x00000009) exists archived, archive_id:1
lj2C: (0x00000009) exists archived, archive_id:1
N5F1: (0x00000001) exists, archive_id:1
nIqm: (0x00000001) exists, archive_id:1
NZY3: (0x00000001) exists, archive_id:1
U6e9: (0x00000001) exists, archive_id:1
urRg: (0x00000001) exists, archive_id:1
uYtQ: (0x00000001) exists, archive_id:1
V5HQ: (0x00000001) exists, archive_id:1
Zl2o: (0x00000001) exists, archive_id:1
zlKI: (0x00000001) exists, archive_id:1
```
This issue did not appear before commit: https://github.com/tstibor/ltsm/commit/175aca88ce628d75dbdfd32c01eedf27fb5e189d
However, there is still the issue (and was before) when default TSM server is installed, and `Maximum Mount Points Allowed: 1`  and threads is 2, then one gets these error:

```
[MESSAGE] 1489052732.015551 [26315] lhsmtool_tsm.c:367 archiving '/lustre/tmp/tmp.fSxVBfWCr6/2aWi' to TSM storage
[ERROR] 1489052732.127264 [26315] tsmapi.c:1195 dsmEndTxn: handle: 2 ANS0266I (RC2302) The dsmEndTxn vote is ABORT, so check the reason field
[ERROR] 1489052732.127297 [26315] tsmapi.c:1196 dsmEndTxn reason: handle: 2 ANS0326E (RC41)   This node has exceeded its maximum number of mount points
[ERROR] 1489052732.127307 [26315] lhsmtool_tsm.c:387 tsm_archive_fpath_fid on '/lustre/tmp/tmp.fSxVBfWCr6/2aWi' failed: Unknown error 2302 (2302)
[MESSAGE] 1489052732.127591 [26315] lhsmtool_tsm.c:321 action completed, notifying coordinator cookie=0x58aeeb8b, FID=[0x200000401:0x2e7a:0x0], err=-2302
```

The _abort-on-error_ flag is just checked in the while loop, however, not set inside the tsm archive, retrieve, etc... operations

**Comment by ironMann** [comment]
I created #14 to fix the error handling a bit. But the problem of `MAXNUMMP` still exists. 

I have not found a way to get it through the API, and even if we could, we want to check remaining number of mounts for a node. Since each of our threads consumes one mount point, we should not create more threads then there are free mountpoints. But, the setup with the server goes fine until you try to end a transaction?!
If this is the case, we can try to do a dummy `TxBegin()/TxEnd()` during thread setup phase, to catch the mount point issue. Any other ideas?

Btw, in #14 I've set `HP_FLAG_RETRY` so each failed action is retried. We need a smarter way to handle this. Maybe have a program parameter `--retry <n>`. Ideas?
With this, and `lctl set_param mdt.$FSNAME-MDT0000.hsm.policy=-NRA`, `sanity.1.sh` passes.

**Comment by ironMann** [comment]
For posterity:
[dsmEndTxn : ANS0326E](http://www-01.ibm.com/support/docview.wss?uid=swg21584672)

[Optimizing the number of multiple sessions to run](https://www.ibm.com/support/knowledgecenter/en/SSGSG7_7.1.1/com.ibm.itsm.perf.doc/r_opt_client_resourceutilization.html)

**Comment by tstibor** [comment]
Just figured out, that we can also use `dsmadmc` as follows to query and extract the information:
`dsmadmc -displ=list -se=my-tsm-server -id=tsm -pass='mypass' -outfile "q node mynode f=d" | grep -oP '(?<=Maximum Mount Points Allowed: ).*'`
I will add a simple script to the repo, so one can quickly determine the proper value for the number of threads. 

In the Lustre lhsmtool_posix.c example they implemented the `HP_FLAG_RETRY` as follows:

```
...
static int ct_fini(struct hsm_copyaction_private **phcp,
                   const struct hsm_action_item *hai, int hp_flags, int ct_rc)
{
        struct hsm_copyaction_private   *hcp;
        char                             lstr[PATH_MAX];
        int                              rc;

        CT_TRACE("Action completed, notifying coordinator "
                 "cookie=%#jx, FID="DFID", hp_flags=%d err=%d",
                 (uintmax_t)hai->hai_cookie, PFID(&hai->hai_fid),
                 hp_flags, -ct_rc);
...
static bool ct_is_retryable(int err)
{
        return err == -ETIMEDOUT;
}
...
fini_major:
        err_major++;

        unlink(dst);
        if (ct_is_retryable(rc))
                hp_flags |= HP_FLAG_RETRY;

        rcf = rc;
```
How about doing it as in the example?

**Comment by joergbehrendt** [comment]
I think we should not use an additianal option like `--retry <n>` to retry an action directly from within the copytool. It is the responsibility from the hsm-controler to eventually retry a failed action and how often it will retry.
Like in the lhsm_posix copytool we should decide by rc if a retry makes sense and then only pass the flag to the coordinator.

Also I dont understand what is the problem with having a much higher thread count than `max_requests` other than some idle threads in the copytool.

**Comment by ironMann** [comment]
@joergbehrendt I agree. I just don't know which TMS error codes should be retried. What happens if we always tell Lustre to retry? Will it keep trying forever?

> Also I dont understand what is the problem with having a much higher thread count than max_requests other than some idle threads in the copytool.

I added a PR #15 to test for this. It will only create as many threads as there are free mount points.

**Comment by joergbehrendt** [comment]
> I just don't know which TMS error codes should be retried. What happens if we always tell Lustre to retry? Will it keep trying forever?

Lustre will keep trying to get that action done forever. Unfortunately there does not seem to be a growing waiting time before lustre fires that action again.
Because of that there will not be many error codes which can be retried. I can only think of connection timeouts and some tsm error codes which explicitly allow a retry (e.g. [DSM_RC_ABORT_SIZESTIMATE_EXCEED](https://www.ibm.com/support/knowledgecenter/SSGSG7_7.1.0/com.ibm.itsm.msgs.client.doc/msg-0013_E.html))

**Comment by tstibor** [comment]
PR https://github.com/tstibor/ltsm/pull/15 works nicely. Just one comment, when the abort-on-error flag
is properly working one should  CT_WARN's rather than CT_ERROR so lhsmtool_tsm keeps finding
the smallest common thread_count without aborting and exiting.

I didn't comment so far on the proposal `2 x thread_count = max_requests`, so there is no problem,
and I also think it is a good balance between thread_count and max_requests.

If I see that correctly, then [sanity-hsm.sh](https://git.hpdd.intel.com/?p=fs/lustre-release.git;a=blob_plain;f=lustre/tests/sanity-hsm.sh;hb=HEAD) contains a bunch of tests
on (+-)NRA flags. We should also test with this script the copytool.
