### ISSUE TITLE
[qtable] deduplication not working on objects with same date

### ISSUE THREAD

**Issue by joergbehrendt** [tstibor/ltsm#20]
If two tsm objects with the same fs/hl/ll key and the same insertion date are processed by the remove_older_obj function in qtable.c both are kept in the hashtable.
This causes the fileapi and my sanity script added in https://github.com/tstibor/ltsm/pull/17/commits/3abba039fb4f4f4152bcbb140c266e331d8dd913 to fail because i always expect exactly one return object.

A simple change of the comparison from 'new.date > old.date' to greater than or equal fixed this problem for me but leads to errors in the test_qtable testsuite.

**Comment by tstibor** [comment]
Fixed in commit: https://github.com/tstibor/ltsm/commit/77f6ccd493ce1e55fba5c2a1dc092c22c0b215f3
