### ISSUE TITLE
Store files in TSM base on a UUID

### ISSUE THREAD

**Issue by dnhodgson** [tstibor/ltsm#23]
Modify this tool so that files could be stored in TSM as a UUID that is attached to the file via an extended attribute. There is issued with using the file path as the ID in TSM as well as the FID and the recommended approach seems to be to use an xattr UUID as the way to track files between HSM levels.

Robinhood already has support for this method.

**Comment by tstibor** [comment]
I guess you are talking about this feature: https://github.com/cea-hpc/robinhood/commit/20206ef1a41ac12ea8e42bb1ac1b49a2d18e2755

Yes, one can add an UUID field to the struct https://github.com/tstibor/ltsm/blob/master/src/lib/tsmapi.h#L98
and set an xattr (_trusted.lhsm.uuid_) of the corresponding file. I will add this feature in the next release. However, from a design point of view, it would make more sense to integrate this feature
in the Lustre HSM API.

**Comment by dnhodgson** [comment]
That's the feature. 

Can you query the TSM based on other attributes besides the path? Or would the UUID within the struct be the ll of the file and the hl would just be "/"?

**Comment by tstibor** [comment]
In the TSM API manual is written:

```
Each object that is stored on the server has a name associated with it. The client
controls the following key components of that name:
* File space name
* High-level name
* Low-level name
* Object type
```
So you are limited to the "/fs/hl/ll" key. One could query for "/\*/*/**" and then filter for UUID
either in the description field or your predefined char[255] field. However that is not efficient at all.
Another approach is store objects in the form "//UUID", so fs:/ hl:/ and ll:/UUID. This enables efficient
querying however you loose the (mount point / directory / filename) naming and thus need to store
this information either in the description field or the char[255] field.

**Comment by dnhodgson** [comment]
Can it be a configuration option to make the choice on how it stores the files in TSM, either via normal full path, or via an xattr?

As I understand it, best practice is that your HSM/Archive shouldn't be relied on as a backup so losing the fullpath data from the TSM isn't going to be a problem. You would have to lose all your frontend stub files and your policy engine database to make the files on tape useless.

**Comment by tstibor** [comment]
Apparently there is no efficient way to implement this issue and at the same time do not lose
the path and file name information. I thus close this issue.
