### ISSUE TITLE
[tsmapi] dsmSendData: tx and data_sent checking

### ISSUE THREAD

**Issue by ironMann** [tstibor/ltsm#4]
I think we're not handling two aspects of `dsmSendData()` [API#141](http://web-docs.gsi.de/~tstibor/tsm/doc/using_the_programming_application_interface.pdf#page=141):

1) stopping the tx if `DSM_RC_WILL_ABORT` is returned
2) checking whether the whole buffer is transmitted by looking at `data_blk.numBytes` after the call. Because I think it's just a socket call, and it might not take all data at once.

What do you think?

I've started to convert the `tsm_archive_generic()` into a FSM, as described in [API#68](http://web-docs.gsi.de/~tstibor/tsm/doc/using_the_programming_application_interface.pdf#page=68). Hopefully it'll make it easier to support batched transactions.

**Comment by tstibor** [comment]
Yes indeed, one should check for the error `rc == DSM_RC_WILL_ABORT`
and then jump to a new `cleanup_endsendobj`  	

```
cleanup_endsendobj:
        rc = dsmEndSendObj(session->handle);
	TSM_DEBUG(session, rc,  "dsmEndSendObj");
	if (rc) {
		TSM_ERROR(session, rc, "dsmEndSendObj");
		success = bFalse;
	}

```
rather than cleaning up the complete transaction.
Thanks for pointing that out.

**Comment by tstibor** [comment]
Converting `tsm_archive_generic()` into FSM as described in [API#68](http://web-docs.gsi.de/~tstibor/tsm/doc/using_the_programming_application_interface.pdf#page=68) is also on the TODO list, forgot to mention that in our mail conversion, though it is written in [README.md](https://github.com/tstibor/ltsm#work-in-progress)
