### ISSUE TITLE
[copytool] Cleanup the consumer threads appropriately

### ISSUE THREAD

**Issue by tstibor** [tstibor/ltsm#6]
The consumer threads are processing requests such as archiving/retrieving/deleting
and the daemon gets a shutdown/c-ctrl signal (by init.d/system.d/user), one should close
the working queue so no new consumer threads can dequeue HSM action items.
In addition, one suppose to wait for a certain period of time such that the current consumer threads can
finished their HSM action items. If the time is passed and they are
still not done, one could to a tsm_disconnect(...), cleanup, etc...

**Comment by ironMann** [comment]
Here's the plan:

- stop `llapi_hsm_copytool_recv()` loop
- wait for txs in flight to finish (**do we need a timeout on this?**)
- cancel all pending requests (and cancelled txs, if any)
- signal threads to finish and `join()` to end them cleanly
- `tsm_disconnect()` and cleanup

Unknown at this moment is if `llapi_hsm_copytool_recv()` will return with `-ESHUTDOWN` on `SIGTERM`. If not, it can be used in non-blocking mode.

Unprocessed items seem to be cancellable with:
`If the copytool does not intend to process the request, it should set is_error to true, and then call llapi_hsm_action_end().`

**Comment by tstibor** [comment]
That sounds perfect and plausible.

Currently, is_error is _false_ in the archive function:
```
static int ct_archive(struct session_t *session)
{
        char fpath[PATH_MAX + 1] = {0};
        int rc;
        int src_fd = -1;

        rc = fid_realpath(opt.o_mnt, &session->hai->hai_fid, fpath, sizeof(fpath));
        if (rc < 0) {
                CT_ERROR(rc, "fid_realpath failed");
                goto cleanup;
        }

        rc = llapi_hsm_action_begin(&session->hcp, ctdata, session->hai, -1, 0, false);
```
and we are not propagating the TSM errors to cancel the request. This also has to be fixed.

**Comment by ironMann** [comment]
> and we are not propagating the TSM errors to cancel the request. This also has to be fixed.

I think that is already handled with [`ct_rc` parameter](https://github.com/tstibor/ltsm/blob/master/src/lhsmtool_tsm.c#L317). 

Preliminary patch is in #10
