### ISSUE TITLE
[tsmapi] Provide low-level ssize_t write(struct session_t *session, const void *buf, size_t count) call

### ISSUE THREAD

**Issue by tstibor** [tstibor/ltsm#7]
One of the GSI experiments asked for a plain
and low-level `ssize_t write(...)` function call, such that data received as a data stream can be seamlessly
written to the TSM server (as a data stream). This is required, when the particle accelerator is running and experimental data is gathered as a data stream.

**Comment by joergbehrendt** [comment]
I created a simple api for direct file like interaction with the tsm-server. In addition a new binary is provided which can be used to pipe data directly into a tsm object or from an object into a local file.
The commit can be found in my dev-fileapi branch: https://github.com/joergbehrendt/ltsm/commit/200924563dbfa1c90e1d985ae340c51b67cd0988

Next step for me is to create a testsuite to check if this fileapi and the previous tsm api behave the same for single file operations.

**Comment by tstibor** [comment]
Implemented in commit https://github.com/tstibor/ltsm/commit/6ad3b87d05703c12e19e12556319f901ff609722
